#!/bin/sh

prg="epm"

print_strings() 
{
cat << END.
&Uninstall
%s is removing...
%s is installing...
END.

$prg play list-all | sed -n 's/^.*  - //p'

}

print_strings | sed 's/^/appinstall::tr("/;s/$/");/'
