appinstall::tr("&Uninstall");
appinstall::tr("%s is removing...");
appinstall::tr("%s is installing...");
appinstall::tr("AnyDesk from the official site");
appinstall::tr("Assistant (Ассистент) from the official site");
appinstall::tr("The hackable text editor from the official site");
appinstall::tr("Brave browser from the official site");
appinstall::tr("The popular and trusted web browser by Google (Stable Channel) from the official site");
appinstall::tr("Chromium with GOST support from the official site");
appinstall::tr("Visual Studio Code from the official site");
appinstall::tr("Discord from the official site");
appinstall::tr("Duplicati from the official site");
appinstall::tr("EAGLE (EDA software) from the official site");
appinstall::tr("Microsoft Edge browser (dev) from the official site");
appinstall::tr("Geogebra 6 from the official site");
appinstall::tr("Контур.Толк (ktalk) from the official site");
appinstall::tr("MS SQL Server 2019 from the official site");
appinstall::tr("MS SQL Server sqlcmd and bcp from the official site");
appinstall::tr("Obsidian from the official site");
appinstall::tr("ONLYOFFICE for Linux from the official site");
appinstall::tr("R7 Office for Linux from the official site");
appinstall::tr("Sferum for Linux from the official site");
appinstall::tr("Skype for Linux - Stable/Release Version from the official site");
appinstall::tr("Spotify client for Linux from the official site");
appinstall::tr("Sputnik browser from the official site");
appinstall::tr("Sublime Text 4 from the official site");
appinstall::tr("TamTam messenger from the official site");
appinstall::tr("Microsoft Teams for Linux from the official site");
appinstall::tr("Teamviewer from the official site");
appinstall::tr("Telegram client from the official site");
appinstall::tr("Viber for Linux from the official site");
appinstall::tr("Vivaldi browser from the official site");
appinstall::tr("XnView MP: Image management from the official site");
appinstall::tr("Yandex browser from the official site");
appinstall::tr("Yandex Disk from the official site");
appinstall::tr("Zoom client from the official site");
