QPushButton::tr("&Uninstall");
QPushButton::tr("Install %s...");
QPushButton::tr("Install AnyDesk from the official site");
QPushButton::tr("Install Assistant (Ассистент) from the official site");
QPushButton::tr("Install Brave browser from the official site");
QPushButton::tr("Install The popular and trusted web browser by Google (Stable Channel) from the official site");
QPushButton::tr("Install Chromium with GOST support from the official site");
QPushButton::tr("Install Visual Studio Code from the official site");
QPushButton::tr("Install Discord from the official site");
QPushButton::tr("Install EAGLE (EDA software) from the official site");
QPushButton::tr("Install Microsoft Edge browser (dev) from the official site");
QPushButton::tr("Install glusterfs7 (or upgrade from glusterfs6)");
QPushButton::tr("Install glusterfs8 (or upgrade from glusterfs7)");
QPushButton::tr("Install glusterfs9 (or upgrade from glusterfs8)");
QPushButton::tr("Fix missed 32 bit package modules on 64 bit system");
QPushButton::tr("Remove all 32 bit packages from 64 bit system");
QPushButton::tr("Install 32 bit wine-etersoft packages on 64 bit system");
QPushButton::tr("Install 32 bit wine packages on 64 bit system");
QPushButton::tr("Install 32 bit wine-vanilla packages on 64 bit system");
QPushButton::tr("Install ONLYOFFICE for Linux from the official site");
QPushButton::tr("Install php7 (or upgrade from php5)");
QPushButton::tr("Install php8 (or upgrade from php7)");
QPushButton::tr("Remove all possible python2 packages");
QPushButton::tr("Install Skype for Linux - Stable/Release Version from the official site");
QPushButton::tr("Install Spotify client for Linux from the official site");
QPushButton::tr("Install TamTam messenger from the official site");
QPushButton::tr("Install Microsoft Teams for Linux from the official site");
QPushButton::tr("Install Teamviewer from the official site");
QPushButton::tr("Install Telegram client from the official site");
QPushButton::tr("Install Viber for Linux from the official site");
QPushButton::tr("Install Vivaldi browser from the official site");
QPushButton::tr("Install Yandex browser from the official site");
QPushButton::tr("Install Yandex Disk from the official site");
QPushButton::tr("Install Zoom client from the official site");
